name: demo_locations
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
#Default
  cupertino_icons: ^1.0.2

#Image
  image_picker: ^0.7.3

#Google Map
  location: ^4.2.0
  google_maps_flutter: ^2.0.8

#Timeline
  timelines: ^0.1.0

#Signature
  signature: ^4.1.1

#Timer 
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  
  uses-material-design: true
